global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
          - 'idonotexists:564'

  - job_name: 'node-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: 
        - 'node01:9100'
        - 'node02:9100'


